name: Scan licenses and vulnerabilities in java project

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  check-vulnerabilities:
    name: Check vulnerabilities
    uses: th2-net/.github/.github/workflows/go-vulnerabilities-scan.yml@migrated-osv-scanner-for-go